__author__ = "Ryan Campbell"
__NetID__ = "317008605"
__GitHubID__ = "cafeclimber"
__SelfGrade__ = "5"
__Challenge__ = "1"
__Answer1__ = "1.00000"
__Answer2__ = "Most likely outcome is heads (1)"

"""
Random Signals and Systems
Course: ECEN 303-502
Maximum Grade: 5pt
"""

import random
import math
import matplotlib.pyplot as plt


ParameterP = 0.7
NumberFlips = 8
NumberTrials = 100000
Trials = []

def biasedcoinflip(p=0.5):
    if random.random() < p:
        return 1
    else:
        return 0


for TrialIndex1 in range(0, NumberTrials):
    Trials.append(biasedcoinflip(ParameterP))

TrialAverage = sum(Trials) / (1.0 * len(Trials))
print('The average number of ones is {0:.4f}.'.format(TrialAverage))

SumTrials = []

for TrialIndex2 in range(0, NumberTrials):
    total = 0.0;
    for trail in range(0, NumberFlips):
        total += biasedcoinflip(ParameterP)
    SumTrials.append(total)

Distribution = []

for OutcomeIndex1 in range(0, NumberFlips + 1):
    Distribution.append(SumTrials.count(OutcomeIndex1) / (1.0 * NumberTrials))

print(repr(Distribution))
print("Sum of all elements in Distribution: %f" % sum(i for i in Distribution))

OutcomeIndex2 = range(0, NumberFlips + 1)
num_bins = len(OutcomeIndex2)
bar_width = 0.8
XticksIndex = [(outcome + (0.5 * bar_width)) for outcome in OutcomeIndex2]
opacity = 0.4

plt.bar(OutcomeIndex2, Distribution, bar_width, alpha=opacity, color='b')
plt.xlabel("Value")
plt.ylabel("Probability")
plt.xticks(XticksIndex, OutcomeIndex2)
plt.show()

"""
Describe what happens to the figure as you vary ParameterP from zero to one.

As ParameterP is shifter from 0 to 1, the center of what appears to be a Gaussian
distribution generated by the coin flips shifts from the 0 to NumberFlips. In 
other words, it changes the most likely amount of heads will be flipped in 
NumberFlips.

What is the sum of the elements in Distribution?
Place your answer in the __Answer1__ variable at the top of this file.

What is the most likely outcome for ParameterP = 0.7 and NumberFlips = 8?
Place your answer in the __Answer2__ variable at the top of this file.


"""
